apiVersion: v1
kind: Service
metadata:
  labels:
    name: samba-ssh
  name: samba-ssh
spec:
  ports:
    - protocol: TCP
      port: 139
      targetPort: 139
      name: samba1
    - protocol: TCP
      port: 445
      targetPort: 445
      name: samba2
    - protocol: UDP
      port: 138
      targetPort: 138
      name: samba3
    - protocol: UDP
      port: 445
      targetPort: 445
      name: samba4
    - protocol: TCP
      port: 22
      targetPort: 22
      name: ssh
  type: NodePort    
  selector:
    name: samba-ssh
---
apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: samba-ssh
  name: samba-ssh-controller
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: samba-ssh
    spec:
      containers:
      - image: 10.15.7.164:8082/samba-ssh
        name: samba-ssh
        ports:
        - name: samba1
          containerPort: 139
        - name: samba2
          containerPort: 138
        - name: samba3
          containerPort: 445
        - name: ssh
          containerPort: 22
